// Corrections to anachronistic or mislabelled polygons in historical-basemaps.
// Each rename was checked against the polygon's actual location (see README).
//
//   years   – snapshots the correction applies to
//   from    – NAME in the source data
//   to      – corrected NAME (references in SUBJECTO / PARTOF are renamed too)
//   subject – optional: overlord to set; null = independent
//   why     – the reason, kept for review

export const CORRECTIONS = [
  // ── Prehistory (10,000–3000 BC) ───────────────────────────────────────
  { years: [-2000], from: 'Dakapeng culture', to: 'Dapenkeng culture', why: 'Misspelling' },
  { years: [-5000], from: '      ', to: 'Cardial Ware culture', why: 'The source leaves NAME blank; its ABBREVN is "Cardial Ware culture"' },
  { years: [-10000, -8000], from: 'Okhotsk culture', to: 'Jōmon', why: 'The Okhotsk culture dates to c. AD 500–1200; northern Japan was Jōmon' },
  { years: [-5000, -4000, -3000, -2000, -1500, -1000, -700, -500, -400], from: 'Ainu', to: 'Jōmon', why: 'Ainu culture took shape c. 13th century AD; before 300 BC Hokkaido was Jōmon' },
  { years: [-323, -300, -200, -100, -1, 100, 200, 300, 400, 500, 600], from: 'Ainu', to: 'Epi-Jōmon', why: 'Ainu culture took shape c. 13th century AD; Hokkaido was Epi-Jōmon c. 300 BC–AD 700' },
  { years: [700, 800, 900, 1000, 1100, 1200], from: 'Ainu', to: 'Satsumon culture', why: 'Ainu culture took shape c. 13th century AD; Hokkaido was Satsumon c. AD 700–1200' },
  { years: [-10000, -8000, -5000, -4000, -3000], from: 'Austronesians', to: 'Island Southeast Asian foragers', why: 'Austronesian speakers left Taiwan only after c. 3000 BC' },
  { years: [-8000, -5000, -4000], from: 'Bantu', to: 'West and Central African foragers', why: 'The Bantu expansion began c. 3000–2500 BC' },
  { years: [-5000], from: 'Hurrian Kingdoms', to: 'Halaf–Ubaid Transitional', why: 'Hurrian states appear in the late 3rd millennium BC; c. 5000 BC northern Mesopotamia was Halaf–Ubaid' },
  { years: [-4000], from: 'Hurrian Kingdoms', to: 'Northern Mesopotamian Chalcolithic', why: 'Hurrian states appear in the late 3rd millennium BC' },
  { years: [-3000], from: 'Hurrian Kingdoms', to: 'Ninevite 5 culture', why: 'Hurrian states appear in the late 3rd millennium BC; c. 3000 BC northern Mesopotamia was Ninevite 5' },
  { years: [-5000, -4000], from: 'Elam', to: 'Susiana culture', why: 'Elam (Proto-Elamite) begins c. 3200 BC; before it the Susiana plain had the Susiana culture' },
  { years: [-5000, -4000], from: 'Norte Chico', to: 'Andean coastal foragers', why: 'Norte Chico begins c. 3500 BC' },
  { years: [-5000], from: 'Naquada I', to: 'Early Neolithic Egypt', why: 'Naqada I begins c. 3900 BC' },
  { years: [-5000], from: 'Funnel-Beaker', to: 'Stroked Pottery culture', why: 'The Funnelbeaker culture begins c. 4300 BC; c. 5000 BC the region had the Stroked Pottery culture' },
  { years: [-5000], from: 'Ghassul', to: 'Wadi Rabah culture', why: 'The Ghassulian begins c. 4500 BC; c. 5000 BC the southern Levant had the Wadi Rabah culture' },
  { years: [-4000], from: 'Indus valley civilization', to: 'Early Indus Valley villages', why: 'The Early Harappan phase begins c. 3300 BC' },
  { years: [-4000, -3000], from: 'Kerma', to: 'Nubian A-Group', why: 'The Kerma culture begins c. 2500 BC; before it Lower Nubia had the A-Group' },

  // ── Ancient ────────────────────────────────────────────────────────────
  { years: [-5000, -4000], from: 'Valdivia', to: 'Andean coastal foragers', why: 'The Valdivia culture begins c. 3800 BC' },
  { years: [-2000], from: 'Hittites', to: 'Hattian and Anatolian city-states', why: 'The Hittite kingdom begins c. 1650 BC; c. 2000 BC central Anatolia had Hattian city-states and Assyrian trading colonies' },
  { years: [-1500], from: 'Phrygians', to: 'Arzawa', why: 'The Phrygians arrived c. 1200 BC; c. 1500 BC western Anatolia was the kingdom of Arzawa' },
  { years: [-1500], from: 'Celtiberians', to: 'Argaric and Iberian Bronze Age cultures', why: 'Celtiberian culture dates from the 1st millennium BC' },
  { years: [-1500, -1000], from: 'Urartu', to: 'Armenian highland chiefdoms', why: 'Urartu was founded c. 860 BC' },
  { years: [-1500], from: 'Wu', to: 'Lower Yangtze Bronze Age cultures', why: 'The state of Wu dates from c. 1000 BC at the earliest' },
  { years: [-1500], from: 'Saba', to: 'South Arabian chiefdoms', why: 'The Sabaean kingdom is attested from c. 1000 BC' },
  { years: [-1000], from: 'Greek city-states', to: 'Dark Age Greece', why: 'Greek city-states (poleis) emerge after c. 800 BC' },
  { years: [-100], from: 'Min-Yue', to: 'Han Empire', why: 'The Han conquered Minyue in 110 BC' },
  { years: [-100], from: 'Nan-Yue', to: 'Han Empire', why: 'The Han conquered Nanyue in 111 BC' },
  { years: [-2000], from: 'Thai', to: 'Longshan and southern Neolithic cultures', why: 'The polygon covers most of China; Tai peoples were one small part of its south' },
  { years: [-200], from: 'Thai', to: 'Dian, Yelang and south-western peoples', why: 'The polygon covers Yunnan, Guizhou and upper Burma, home to the Dian and Yelang kingdoms' },
  { years: [-400], from: 'Proto-Thai cultures', to: 'Northern Chinese states and pastoralists', why: 'The polygon covers North China and Manchuria, far from any Tai-speaking peoples' },
  { years: [-200, -100], from: 'minor states', to: 'Anatolian and Armenian kingdoms', why: 'The polygon covers Anatolia and Armenia: Pontus, Cappadocia, Bithynia and Armenia' },
  { years: [-10000, -8000, -4000, -3000, -2000], from: 'Hunters-gatherers', to: 'Island hunter-gatherers', why: 'Spelling; the polygon covers Sardinia, Corsica and Madagascar' },
  { years: [-4000], from: 'Egypt', to: 'Naqada culture', why: 'Egypt was unified c. 3100 BC; 4000 BC is the predynastic Naqada period' },
  { years: [-4000], from: 'Minoan', to: 'Neolithic Crete', why: 'Minoan civilisation begins c. 3100 BC' },
  { years: [-1500], from: 'Greek city-states', to: 'Mycenaean Greece', why: 'City-states (poleis) emerge after c. 800 BC' },
  { years: [-1500], from: 'Kingdom of David and Solomon', to: 'Canaanite city-states', why: 'The United Monarchy dates to c. 1000–930 BC' },
  { years: [-700], from: 'Kingdom of David and Solomon', to: 'Levantine kingdoms', why: 'The United Monarchy split c. 930 BC; Israel fell to Assyria in 722 BC' },
  { years: [-1000, -700], from: 'Hittites', to: 'Syro-Hittite states', why: 'The Hittite Empire collapsed c. 1180 BC' },
  { years: [-400], from: 'Xiongnu', to: 'Slab Grave culture', why: 'The Xiongnu confederation formed c. 209 BC' },
  { years: [-100], from: 'Kushan Empire', to: 'Yuezhi and Indo-Scythians', why: 'The Kushan Empire was founded c. AD 30' },
  { years: [-323, -300, -200], from: 'Teotihuacan', to: 'Basin of Mexico chiefdoms', why: 'Teotihuacan grew into a city from c. 100 BC' },
  { years: [-100], from: 'Mauryan Empire', to: 'Shunga Empire', why: 'The Maurya dynasty ended in 185 BC' },
  { years: [-1], from: 'Moche', to: 'Gallinazo culture', why: 'Moche culture begins c. AD 100' },

  // ── Late antiquity & medieval ──────────────────────────────────────────
  { years: [500, 600], from: 'Tuʻi Tonga Empire', to: 'Tongan chiefdoms', why: 'The Tuʻi Tonga dynasty dates from c. AD 950' },
  { years: [600, 700], from: 'Teotihuacan', to: 'Post-Teotihuacan Basin of Mexico', why: 'Teotihuacan’s centre burned c. 550 and the city lost its power' },
  { years: [700], from: 'Paekche', to: 'Silla', why: 'Baekje fell to Silla and Tang in 660' },
  { years: [1400], from: 'Bulgar Khanate', to: 'Ottoman Empire', why: 'The Ottomans conquered the last Bulgarian states in 1393–96' },
  { years: [700], from: 'Koguryo', to: 'Balhae', why: 'Goguryeo fell in 668; Balhae was founded in its northern lands in 698' },
  { years: [800], from: 'Silia', to: 'Silla', why: 'Misspelling' },
  { years: [900], from: 'Yamato', to: 'Japan', why: 'The Yamato period ended with the move to Heian-kyō in 794' },
  { years: [900], from: 'Avars', to: 'Magyars', why: 'The Avar Khaganate fell c. 800; the Magyars took the Carpathian basin in 895–900' },
  { years: [1000], from: 'Khazars', to: 'Alania', why: 'The Khazar Khaganate fell in 965–969; the north Caucasus was the kingdom of Alania' },
  { years: [1000, 1100, 1200], from: 'Mali', to: 'Kangaba (early Mali)', why: 'The Mali Empire was founded c. 1235' },
  { years: [1100], from: 'Pratiharas', to: 'Gahadavala kingdom', why: 'The Pratiharas fell c. 1036; Kannauj was ruled by the Gahadavalas from c. 1090' },
  { years: [1100, 1200], from: 'Pyu state', to: 'Pagan', why: 'The Pyu city-states were absorbed by Pagan by the 11th century' },
  { years: [1200], from: 'Imperial Japan (Fujiwara)', to: 'Shogun Japan (Kamakura)', why: 'The Kamakura shogunate was founded in 1185' },
  { years: [1200], from: 'Buyid dynasty', to: 'Kingdom of Kashmir', why: 'The polygon covers Kashmir; the Buyids ruled Iran and Iraq and fell in 1062' },
  { years: [1279], from: 'Kediri', to: 'Singhasari', why: 'Kediri fell to Singhasari in 1222' },
  { years: [1300, 1400], from: 'Kediri', to: 'Majapahit', why: 'Majapahit was founded in 1293' },
  { years: [300, 400], from: 'Satavahanihara', to: 'Vakataka and Ikshvaku kingdoms', why: 'The Satavahana dynasty ended c. 225' },
  { years: [400], from: 'Meroe', to: 'Post-Meroitic Nubia', why: 'The kingdom of Meroe collapsed c. 350' },
  { years: [800], from: 'Rajput Clans and Small States', to: 'Mon, Pyu and Tai states', why: 'The polygon covers mainland South-East Asia, not Rajasthan' },
  { years: [900], from: 'Azandes', to: 'Ubangian and Nilotic peoples', why: 'The Azande state formed in the 18th century; the polygon covers the southern Sudan and Ubangi' },
  { years: [1000], from: 'Peshemegs', to: 'Pechenegs', why: 'Misspelling' },
  { years: [1200], from: 'Ifat', to: 'Sultanate of Shewa', why: 'The Ifat sultanate replaced Shewa c. 1285' },
  { years: [1100, 1200], from: 'Tiahuanaco Empire', to: 'Aymara kingdoms', why: 'Tiwanaku collapsed c. AD 1000–1100; the Aymara kingdoms followed' },
  { years: [1100, 1200], from: 'Huari Empire', to: 'Andean states and chiefdoms', why: 'The Wari state collapsed c. AD 1000' },
  { years: [300], from: 'Parthian Empire', to: 'Sasanian Empire', why: 'The Sasanians overthrew the Parthians in AD 224' },
  { years: [500], from: 'Western Roman Empire', to: 'Romano-British kingdoms', why: 'The Western Empire ended in 476; the polygon covers western Britain' },
  { years: [500], from: 'Jin Empire', to: 'Southern Qi', why: 'The Jin dynasty ended in 420; south China was ruled by the Southern Qi (479–502)' },
  { years: [700], from: 'Sui Empire', to: 'Tang Empire', why: 'The Sui dynasty ended in 618' },
  { years: [700], from: 'Sasanian Empire', to: 'Umayyad Caliphate', why: 'The Sasanian Empire fell to the Arab conquest in 651; the polygon covers Iran and Iraq' },
  { years: [700], from: 'Sasanian dependencies', to: 'Umayyad Caliphate', why: 'Sasanian rule in Yemen ended c. 628; the polygon covers Yemen' },
  { years: [1200], from: 'Mongol Empire', to: 'Mongol tribes', why: 'The Mongol Empire was proclaimed in 1206' },
  { years: [1200], from: 'Toltec Empire', to: 'Chichimec states', why: 'Tula fell c. 1168' },
  { years: [1279, 1300], from: 'Seljuk Caliphate', to: 'Sultanate of Rum', why: 'The Seljuks never held the caliphate; central Anatolia was the Sultanate of Rum (to 1308)' },
  { years: [1400], from: 'Seljuk Caliphate', to: 'Anatolian beyliks', why: 'The Sultanate of Rum ended in 1308' },
  { years: [1300], from: 'Chola Empire', to: 'Pandya state', why: 'The Chola dynasty ended in 1279; the region passed to the Pandyas' },
  { years: [1400], from: 'Chola Empire', to: 'Vijayanagara', why: 'The Chola dynasty ended in 1279; Vijayanagara ruled the region from the 1360s' },
  { years: [1400], from: 'Srivijaya Empire', to: 'Majapahit', why: 'Srivijaya fell to Majapahit in 1377' },
  { years: [1400], from: 'Great Khanate', to: 'Ming Empire and Northern Yuan', subject: null, why: 'The Yuan dynasty fell in 1368; the polygon covers both Ming China and Mongolia' },
  { years: [1400], from: 'Shogun Japan (Kamakura)', to: 'Ashikaga Shogunate', why: 'The Kamakura shogunate ended in 1333' },
  ...['Tibet', 'Novgorod', 'Blue Horde', 'White Horde', 'Chagatai Khanate'].map((n) => ({
    years: [1400], from: n, to: n, subject: null, why: 'No unified Mongol Empire existed in 1400',
  })),

  { years: [1200], from: 'Liao', to: 'Jin dynasty (Jurchen)', why: 'The Liao fell to the Jurchen Jin in 1125' },
  { years: [1200], from: 'Fatimid Caliphate', to: 'Ayyubid Sultanate', why: 'Saladin ended the Fatimid Caliphate in 1171' },
  { years: [1200], from: 'Sultanate of Delhi', to: 'Ghurid Empire', why: 'The Delhi Sultanate was founded in 1206; in 1200 northern India was held by the Ghurids' },
  { years: [1200], from: 'Buwayhid Emirates', to: 'Khwarazmian Empire', why: 'The Buyids fell in 1062; the Khwarazmshahs took central Iran in 1194' },
  { years: [1200], from: 'Khwarazmian dynasty', to: 'Khwarazmian Empire', why: 'Same state as the polygon renamed above' },
  { years: [900], from: 'Tibetan Empire', to: 'Tibet', why: 'The Tibetan Empire collapsed in 842' },
  { years: [1100], from: 'Kingdom of Sukhotai', to: 'Tai chiefdoms', why: 'Sukhothai was founded c. 1238' },
  { years: [1300], from: 'Pagan', to: 'Myinsaing and Pinya', why: 'The Pagan kingdom ended in 1297' },
  { years: [1400], from: 'Pagan', to: 'Ava', why: 'The Pagan kingdom ended in 1297; the Ava kingdom ruled Upper Burma from 1364' },
  // ── Early modern ───────────────────────────────────────────────────────
  { years: [1700, 1715], from: 'Arakan (Indian princely state)', to: 'Arakan', why: 'Arakan (Mrauk U) was an independent kingdom until Burma conquered it in 1784' },
  { years: [1783, 1800, 1815], from: 'Sotho', to: 'Niger Delta city-states', why: 'The polygon lies in the Niger Delta (Bonny, Brass, Kalabari); the Sotho live in southern Africa' },
  { years: [1815], from: '       ', to: 'United Kingdom of the Netherlands', why: 'The source leaves NAME blank; its SUBJECTO is the United Kingdom of the Netherlands' },
  { years: [1492, 1500], from: 'Philippines', to: 'Philippine barangay states', why: 'The Philippines were named and united under Spanish rule from 1565' },
  { years: [1650, 1700, 1715, 1783], from: 'Malaya', to: 'Malay sultanates', why: 'British Malaya dates from 1786 at the earliest' },
  { years: [1600], from: 'Orissa', to: 'Mughal Empire', why: 'The Mughals conquered Orissa in 1592' },
  { years: [1783], from: 'Golconda', to: "Nizam's Dominions", why: 'Golconda fell to the Mughals in 1687; the region became the Nizam of Hyderabad’s state from 1724' },
  { years: [1783], from: 'Bengal', to: 'British East India Company', why: 'The Company took control of Bengal in 1757–65' },
  { years: [1800], from: 'Circars', to: 'British East India Company', why: 'The Northern Circars were Company territory from 1766' },
  { years: [1815], from: 'Somalia', to: 'Somali sultanates', why: 'Somalia as a state dates from 1960' },
  { years: [1600], from: 'Inca Empire', to: 'Viceroyalty of Peru', subject: 'Spain', why: 'The Inca Empire fell in 1533 (last Neo-Inca stronghold 1572)' },
  { years: [1600], from: 'Songhai', to: 'Pashalik of Timbuktu', subject: 'Morocco', why: 'The Songhai Empire fell to Morocco in 1591; the polygon covers the Niger bend around Gao and Timbuktu' },
  { years: [1650, 1700, 1715, 1783, 1800], from: 'Songhai', to: 'Dendi Kingdom', why: 'The Songhai Empire fell in 1591; its successor in the south was Dendi' },
  { years: [1700, 1715], from: 'Mali', to: 'Kangaba (Mali remnant)', why: 'The Mali Empire broke up c. 1670' },
  { years: [1783, 1800, 1815], from: 'Zulu', to: 'Northern Nguni chiefdoms', why: 'The Zulu Kingdom was founded by Shaka in 1816' },
  { years: [1650, 1700, 1715, 1815, 1880, 1900], from: 'Manchu Empire', to: 'Qing Empire', why: 'Same state is called "Qing Empire" in other snapshots' },

  { years: [1700], from: 'Post-Ming Warlords', to: 'Qing Empire', why: 'The Qing crushed the Three Feudatories in 1681' },
  { years: [1715], from: 'Egypt', to: 'Ottoman Egypt', subject: 'Ottoman Empire', why: 'An Ottoman province from 1517' },
  // ── Modern ─────────────────────────────────────────────────────────────
  { years: [1880], from: 'Ivory Coast', to: 'Akan and Kru states', why: 'France made the Ivory Coast a colony in 1893; in 1880 the region was ruled by Akan kingdoms and Kru communities' },
  { years: [1900], from: 'Tukular Caliphate', to: 'French West Africa', subject: 'France', why: 'France defeated the Toucouleur Empire in 1890–93' },
  { years: [1900], from: 'Second Samori Empire', to: 'French West Africa', subject: 'France', why: 'France captured Samori Ture in 1898' },
  { years: [1914, 1920, 1930, 1938], from: 'Malawi', to: 'Nyasaland', subject: 'United Kingdom', why: 'Nyasaland became independent as Malawi in 1964' },
  { years: [1930, 1938], from: 'Hail', to: 'Saudi Arabia', why: 'Ibn Saud took Ha’il from the Rashidis in 1921' },
  { years: [1920, 1930, 1938], from: 'Togo', to: 'French Togoland', subject: 'France', why: 'A French mandate until independence in 1960' },
  { years: [1920, 1930, 1938], from: 'Guinea-Bissau', to: 'Portuguese Guinea', subject: 'Portugal', why: 'A Portuguese colony until 1974' },
  { years: [1914, 1920, 1930, 1938], from: 'Equatorial Guinea', to: 'Spanish Guinea', subject: 'Spain', why: 'A Spanish colony until 1968' },
  { years: [1914, 1920, 1930, 1938], from: 'Lesotho', to: 'Basutoland', subject: 'United Kingdom', why: 'Basutoland became independent as Lesotho in 1966' },
  { years: [1914], from: 'Djibouti', to: 'French Somaliland', subject: 'France', why: 'French Somaliland until 1967; independent as Djibouti in 1977' },
  { years: [1960], from: 'Djibouti', to: 'French Somaliland', subject: 'France', why: 'French Somaliland until 1967; independent as Djibouti in 1977' },
  { years: [1900], from: 'Benin', to: 'Southern Nigeria', subject: 'United Kingdom', why: 'Britain conquered the Kingdom of Benin in 1897' },
  { years: [1960], from: 'Benin', to: 'Dahomey', why: 'Independent as Dahomey in 1960; renamed Benin in 1975' },
  { years: [1960], from: 'Burkina Faso', to: 'Upper Volta', why: 'Independent as Upper Volta in 1960; renamed Burkina Faso in 1984' },
  { years: [1920, 1930], from: 'Ghana', to: 'Gold Coast', subject: 'United Kingdom', why: 'The Gold Coast became independent as Ghana in 1957' },
  { years: [1920, 1930, 1960], from: 'Zimbabwe', to: 'Southern Rhodesia', subject: 'United Kingdom', why: 'Zimbabwe became independent in 1980' },
  { years: [1914, 1920, 1930, 1938, 1945, 1960], from: 'Botswana', to: 'Bechuanaland', subject: 'United Kingdom', why: 'The Bechuanaland Protectorate became independent as Botswana in 1966' },
  { years: [1960], from: 'Western Sahara', to: 'Spanish Sahara', subject: 'Spain', why: 'A Spanish colony until 1975' },
  { years: [1945], from: 'Guinea', to: 'French Guinea', subject: 'France', why: 'A French colony until 1958' },
  { years: [1938], from: 'Hejaz', to: 'Saudi Arabia', why: 'The Hejaz was united into Saudi Arabia in 1932' },
  { years: [1900], from: 'Harer (Egypt)', to: 'Ethiopia', why: 'Egypt left Harar in 1885; Ethiopia took it in 1887' },
  { years: [1900], from: 'First Samori Empire', to: 'French West Africa', subject: 'France', why: 'France captured Samori Ture in 1898' },
  { years: [1900], from: 'Kanem-Bornu', to: 'Bornu', why: 'The Sayfawa dynasty fell to Rabih in 1893; Bornu was divided among Britain, France and Germany in 1900' },
  { years: [1914], from: 'Armenia', to: 'Russian Empire', why: 'Armenia became independent in 1918' },
  { years: [1914], from: 'Azerbaijan', to: 'Russian Empire', why: 'Azerbaijan became independent in 1918' },
  { years: [1914], from: 'Georgia', to: 'Russian Empire', why: 'Georgia was annexed by Russia in 1801; independent in 1918' },
  { years: [1914], from: 'British Protectorate', to: 'Oman and the Aden Protectorate', why: 'The polygon covers Oman and southern Arabia under British protection' },
  { years: [-1500], from: 'Zhoa', to: 'Shang', why: 'Misspelling of Zhou; c. 1500 BC the Yellow River plain was ruled by the Shang (the Zhou conquest was c. 1046 BC)' },
  { years: [-1000, -700], from: 'Zhoa', to: 'Zhou', why: 'Misspelling of Zhou' },
  { years: [1938], from: 'Israel', to: 'Mandatory Palestine (GB)', why: 'Israel was founded in 1948; in 1938 this was the British Mandate' },
  { years: [1783], from: 'India', to: 'British East India Company', why: 'Company territory (its SUBJECTO says so); the Republic of India dates from 1947' },
  { years: [1900, 1938], from: 'India', to: 'British Raj', subject: 'United Kingdom', why: 'Fragments of British India; India became independent in 1947' },
  { years: [1920, 1930, 1938], from: 'Malaysia', to: 'British Malaya', subject: 'United Kingdom', why: 'Malaya was British until 1957; Malaysia was formed in 1963' },
  { years: [1960], from: 'Malaysia', to: 'Malaya', subject: null, why: 'Malaya became independent in 1957; Malaysia was formed in 1963' },
  { years: [1880], from: 'Kingdom of Brazil', to: 'Empire of Brazil', why: 'Brazil was an empire from 1822 to 1889' },
  { years: [1900], from: 'Kingdom of Brazil', to: 'Brazil', why: 'Brazil became a republic in 1889' },
  { years: [1783, 1800], from: 'Paraguay', to: 'Viceroyalty of the Río de la Plata', subject: 'Spain', why: 'Paraguay became independent in 1811; before that it was part of the Viceroyalty of the Río de la Plata' },
  // The 1945 snapshot draws many colonies and mandates as the states they became later.
  ...[
    ['Israel', 'Mandatory Palestine (GB)', 'United Kingdom', 'Israel was founded in 1948'],
    ['India', 'British Raj', 'United Kingdom', 'India became independent in 1947'],
    ['Pakistan', 'British Raj', 'United Kingdom', 'Pakistan was founded in 1947'],
    ['Bangladesh', 'British Raj', 'United Kingdom', 'Bengal was part of British India until 1947; Bangladesh dates from 1971'],
    ['Sri Lanka', 'Ceylon', 'United Kingdom', 'Ceylon became independent in 1948 and Sri Lanka in 1972'],
    ['Burma', 'Burma', 'United Kingdom', 'Burma became independent in 1948'],
    ['Malaysia', 'British Malaya', 'United Kingdom', 'Malaya became independent in 1957, Malaysia in 1963'],
    ['Brunei', 'Brunei', 'United Kingdom', 'A British protectorate until 1984'],
    ['Jordan', 'Transjordan', 'United Kingdom', 'A British mandate until 1946'],
    ['Kuwait', 'Kuwait', 'United Kingdom', 'A British protectorate until 1961'],
    ['Qatar', 'Qatar', 'United Kingdom', 'A British protectorate until 1971'],
    ['United Arab Emirates', 'Trucial States', 'United Kingdom', 'The UAE was formed in 1971 from the British-protected Trucial States'],
    ['Philippines', 'Philippines', 'USA', 'A US commonwealth until 1946'],
    ['Benin', 'Dahomey', 'France', 'French colony of Dahomey until 1960; renamed Benin in 1975'],
    ['Burkina Faso', 'Upper Volta', 'France', 'French colony of Upper Volta until 1960; renamed Burkina Faso in 1984'],
    ['Cameroon', 'French Cameroons', 'France', 'A French trust territory until 1960'],
    ['Central African Republic', 'Ubangi-Shari', 'France', 'French colony of Ubangi-Shari until 1960'],
    ['Congo', 'Middle Congo', 'France', 'French colony of Middle Congo until 1960'],
    ['Gabon', 'Gabon', 'France', 'A French colony until 1960'],
    ['Togo', 'French Togoland', 'France', 'A French trust territory until 1960'],
    ['Djibouti', 'French Somaliland', 'France', 'French Somaliland until 1967; independent as Djibouti in 1977'],
    ['Namibia', 'South West Africa', 'South Africa', 'Ruled by South Africa until 1990'],
    ['Rwanda', 'Ruanda-Urundi', 'Belgium', 'A Belgian trust territory until 1962'],
    ['Burundi', 'Ruanda-Urundi', 'Belgium', 'A Belgian trust territory until 1962'],
    ['Equatorial Guinea', 'Spanish Guinea', 'Spain', 'A Spanish colony until 1968'],
    ['Western Sahara', 'Spanish Sahara', 'Spain', 'A Spanish colony until 1975'],
    ['Guyana', 'British Guiana', 'United Kingdom', 'British Guiana until 1966 (the source gives the Netherlands as overlord)'],
    ['Suriname', 'Surinam', 'Netherlands', 'A Dutch colony until 1975'],
    ['Belize', 'British Honduras', 'United Kingdom', 'A British colony until 1981'],
    ['Bahamas', 'Bahamas', 'United Kingdom', 'A British colony until 1973'],
    ['Barbados', 'Barbados', 'United Kingdom', 'A British colony until 1966'],
    ['Trinidad', 'Trinidad and Tobago', 'United Kingdom', 'A British colony until 1962'],
    ['Grenada', 'Grenada', 'United Kingdom', 'A British colony until 1974'],
    ['Dominica', 'Dominica', 'United Kingdom', 'A British colony until 1978'],
    ['Saint Lucia', 'Saint Lucia', 'United Kingdom', 'A British colony until 1979'],
    ['Saint Vincent and the Grenadines', 'Saint Vincent', 'United Kingdom', 'A British colony until 1979'],
    ['Saint Kitts and Nevis', 'Saint Kitts-Nevis-Anguilla', 'United Kingdom', 'A British colony until 1983'],
    ['Antigua and Barbuda', 'Antigua', 'United Kingdom', 'A British colony until 1981'],
    ['Papua New Guinea', 'Territory of Papua and New Guinea', 'Australia', 'Ruled by Australia until 1975'],
    ['Samoa', 'Western Samoa', 'New Zealand', 'A New Zealand trust territory until 1962'],
    ['Fiji', 'Fiji', 'United Kingdom', 'A British colony until 1970'],
  ].map(([from, to, subject, why]) => ({ years: [1945], from, to, subject, why })),
  { years: [1914], from: 'Manchu Empire', to: 'Republic of China', why: 'The Qing dynasty ended in 1912' },
  { years: [1945], from: 'Mali', to: 'French Sudan', why: 'Mali became independent in 1960' },
  { years: [1945], from: 'Zaire', to: 'Belgian Congo', subject: 'Belgium', why: 'Independent in 1960; renamed Zaire only in 1971' },
  { years: [1960], from: 'Zaire', to: 'Republic of the Congo (Léopoldville)', why: 'Renamed Zaire in 1971' },
  { years: [1920], from: 'USSR', to: 'Russian SFSR', why: 'The USSR was founded in December 1922' },
  { years: [1960], from: 'Tibet', to: 'Tibet (China)', subject: 'China', why: 'Annexed by the People’s Republic of China in 1950' },
  { years: [1920], from: 'Iran', to: 'Persia', why: 'The Qajar dynasty ruled until 1925; the country was renamed Iran in 1935' },
  ...['Georgia', 'Armenia', 'Azerbaijan'].map((n) => ({
    years: [1920], from: n, to: n, subject: null, why: 'Independent in early 1920; joined the USSR at its founding in 1922',
  })),
  { years: [1930], from: 'White Russia', to: 'USSR', why: 'The whole Soviet Union was mislabelled with the name of Belarus' },
  { years: [1930], from: 'Far Eastern SSR', to: 'USSR', why: 'The Far Eastern Republic joined Soviet Russia in 1922' },
  { years: [1994, 2000, 2010], from: 'Byelarus', to: 'Belarus', why: 'Official name since 1991' },
  { years: [1994, 2000], from: 'Serbia', to: 'FR Yugoslavia', why: 'Serbia and Montenegro formed one state until 2006' },
  { years: [1994, 2000], from: 'Montenegro', to: 'FR Yugoslavia', why: 'Serbia and Montenegro formed one state until 2006' },
  { years: [2000, 2010], from: 'Zaire', to: 'DR Congo', why: 'Renamed in 1997' },
  { years: [2000, 2010], from: 'Hong Kong', to: 'Hong Kong', subject: 'China', why: 'Returned to China in 1997' },
];

// Polygons dropped entirely: not polities, and only named in some snapshots,
// so they flicker in and out as a "country" when scrubbing.
export const REMOVALS = [
  { years: [1945, 1960], name: 'Antarctica', why: 'Never a state; the land is drawn by the coastline layer at every date' },
  { years: [-5000], name: 'Kelteminar', why: 'A copy of the Central Asian Kelteminar culture drawn on New Zealand, which was uninhabited until c. AD 1280' },
];

// Modern snapshots use Natural Earth 1:10m country shapes. These Natural Earth
// countries keep their own name (or take a fixed one) instead of the source's.
export const MODERN_OVERRIDES = {
  1994: { 'Timor-Leste': 'Indonesia', 'S. Sudan': 'Sudan', Kosovo: 'FR Yugoslavia', Macao: 'Macao' },
  2000: { 'Timor-Leste': 'East Timor', 'S. Sudan': 'Sudan', Kosovo: 'FR Yugoslavia', Macao: 'Macao' },
  2010: { 'Timor-Leste': 'Timor-Leste', 'S. Sudan': 'Sudan', Kosovo: 'Kosovo', Macao: 'Macao' },
};

export const MODERN_SUBJECTS = {
  1994: { Macao: 'Portugal', 'Hong Kong': 'United Kingdom', 'East Timor': null },
  2000: { Macao: 'China', 'East Timor': 'United Nations' },
  2010: { Macao: 'China' },
};
